version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: develop
    reviewers:
      - turnrdev
    assignees:
      - turnrdev
    labels:
      - "dependencies"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 1
    target-branch: develop
    commit-message:
      prefix: "(i18n)"
    reviewers:
      - "TrainerDex/translation"
    labels:
      - "i18n"
