version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: main
    reviewers:
      - turnrdev
    assignees:
      - turnrdev
    commit-message:
      prefix: "deps: "
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: main
    reviewers:
      - turnrdev
    assignees:
      - turnrdev
    commit-message:
      prefix: "chore: "
    labels:
      - "dependencies"
