[tool.black]
    line-length = 117
    target-version = ['py310']
    include = '\.py$'
    exclude = '''
    /(
          \.eggs
        | \.git
        | \.hg
        | \.mypy_cache
        | \.tox
        | \.venv
        | _build
        | buck-out
        | build
        | dist
    )/
    '''