name: Danger
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: danger/python@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
