name: Lint & Style Check

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Set up Python 3.11
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: pip install pipenv && pipenv install --dev
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          pipenv run flake8 . --count --exit-zero --max-complexity=10 --statistics
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Set up Python 3.11
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: pip install pipenv && pipenv install --dev
      - name: Style with Black
        run: pipenv run black --check --diff --color .
